services:
  - type: web
    name: french-prononciation-app-backend
    env: python
    plan: free
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'python app.py'
    envVars:
      - key: NODE_ENV
        value: production
