services:
  - type: web
    name: prononciation-francaise
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:5000 app:app
    envVars:
      - key: FLASK_ENV
        value: production